name: testrepo-tests
on: [push]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
      - name : Cache Download
        id: cache-fsdownload
        uses: actions/cache@v3
        env:
          cache-name: cache-fs
        with:
          path: ~/TESTDATA
          key:
            TEST1.txt
      - run: git submodule update --init --recursive

      - if: ${{ steps.cache-fs.outputs.cache-hit != 'true' }}
        name: Download FS
        run: pip install gdown; mkdir ~/TESTDATA; gdown https://drive.google.com/file/d/18W9q3em4ruRisqsNnwhG4kXlZJDP-IVD/view?usp=sharing -O ~/TESTDATA/TEST1.txt --fuzzy

